#!/bin/bash

echo ""
echo "╔════════════════════════════════════════════════════════╗"
echo "║   🚀 ØLIV WEBSITE - DEPLOYMENT INSTRUCTIONS           ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "Dit website er klar til deployment! Vælg en metode:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ METODE 1: Vercel (Anbefalet - 2 minutter)"
echo "   → Gå til: https://vercel.com"
echo "   → Log ind med GitHub"
echo "   → Import repository: JonasBS/-liv"
echo "   → Klik Deploy"
echo "   → ✅ DONE!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ METODE 2: Netlify Drop (Nemmest - 30 sekunder)"
echo "   → Gå til: https://app.netlify.com/drop"
echo "   → Drag index.html på siden"
echo "   → ✅ DONE!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ METODE 3: GitHub Pages (Gratis)"
echo "   → Gå til: https://github.com/JonasBS/-liv"
echo "   → Settings → Pages"
echo "   → Source: Deploy from branch"
echo "   → Branch: cursor/enhance-farm-hospitality-website-experience-e313"
echo "   → Folder: / (root)"
echo "   → Save"
echo "   → ✅ DONE!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Se DEPLOY-NOW.md for detaljeret guide"
echo ""
echo "🌐 Repository: https://github.com/JonasBS/-liv"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
